# Generated by Django 5.0.3 on 2024-04-04 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srsapp', '0004_alter_subjects_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srsapp.course'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(default='True', max_length=250)),
                ('fname', models.CharField(default='True', max_length=250)),
                ('mname', models.CharField(default='True', max_length=250)),
                ('lname', models.CharField(default='True', max_length=250)),
                ('gender', models.CharField(default='True', max_length=250)),
                ('gname', models.CharField(default='True', max_length=250)),
                ('ocp', models.CharField(default='True', max_length=250)),
                ('income', models.CharField(default='True', max_length=250)),
                ('category', models.CharField(default='True', max_length=250)),
                ('ph', models.CharField(default='True', max_length=250)),
                ('mobno', models.CharField(default='True', max_length=250)),
                ('email', models.EmailField(max_length=100)),
                ('country', models.CharField(default='True', max_length=250)),
                ('state', models.CharField(default='True', max_length=250)),
                ('city', models.CharField(default='True', max_length=250)),
                ('padd', models.TextField(blank=True, default=0)),
                ('cadd', models.TextField(blank=True, default=0)),
                ('class1', models.CharField(default='True', max_length=250)),
                ('board1', models.CharField(default='True', max_length=250)),
                ('roll1', models.CharField(default='True', max_length=250)),
                ('pyear1', models.CharField(default='True', max_length=250)),
                ('class2', models.CharField(default='True', max_length=250)),
                ('board2', models.CharField(default='True', max_length=250)),
                ('roll2', models.CharField(default='True', max_length=250)),
                ('pyear2', models.CharField(default='True', max_length=250)),
                ('sub1', models.CharField(default='True', max_length=250)),
                ('marks1', models.IntegerField()),
                ('fmarks1', models.IntegerField()),
                ('sub2', models.CharField(default='True', max_length=250)),
                ('marks2', models.IntegerField()),
                ('fmarks2', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srsapp.course')),
                ('subjects_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srsapp.subjects')),
            ],
        ),
    ]
